### ISSUE TITLE
CTRL-C No Longer Closes Program

### ISSUE THREAD

**Issue by Linrono** [Mikadily/poloniexlendingbot#169]
I used to use CTRL-C to close the bot when I was done running it and wanted it to close cleanly. This no longer seems to work. The bot will just sit there as far as I can tell. It does say that it is stopping the webserver, but that seems to be it. If you need any more information please let me know.

**Comment by Evanito** [comment]
From @praeluceo:
I wanted to chime in and thank you for contributing as well! When debugging config file changes, this has been a tedious delay, and I knew it had to be something of a straight-forward fix, but not one I was able to implement, so thank you!!! Tested as working for 1 hour on my setup.

One gotcha that may need more investigation, is that when hitting ctrl+c to stop the bot, it hangs now at:

> $ python lendingbot.py
> Welcome to Poloniex Lending Bot
> Started WebServer, lendingbot status available at http://localhost:8000/lendingbot.html
> ^CStopping WebServer

And I have to kill the process manually. I have bisected the issue to be introduced as of the latest commit.

* The ^C behavior in commit d6ab2fa3daab6951dbf3c43ee9875a473b786872:
** Bot hangs, PID has to be killed, this is the behavior mentioned above. Additionally, the bot doesn't print the "Welcome to Poloniex Lending Bot" motd.
* The ^C behavior in the previous commit, 73b68cb717fa93ef9a9280dbd382a1f8876d27f7:
** The bot immediately closes, but with an error:
```
$ python lendingbot.py
^CTraceback (most recent call last):
  File "lendingbot.py", line 48, in <module>
    Analysis.init(Config, api, Data)
  File "/home/ronald/bots/poloniexlendingbot/modules/MarketAnalysis.py", line 35, in init
    api.api_query("returnLoanOrders", {'currency': currency, 'limit': '5'})
  File "/home/ronald/bots/poloniexlendingbot/modules/Poloniex.py", line 65, in api_query
    ret = urllib2.urlopen(urllib2.Request(req_url))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 566, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```
* The ^C Behavior at commit 78d1549bc0e9bb4566733afdcfdcdb1b4e6bf973:
** Everything (startup and shutdown) appear to occur as expected.

Bisection suggests the hang may be related to the fix to #155  or #151.
