### ISSUE TITLE
Can't find *.cfg

### ISSUE THREAD

**Issue by judokan9** [Mikadily/poloniexlendingbot#172]
Hello today i got following issue,

```
Obtaining settings from config file.
Traceback (most recent call last):
  File "bot/poloniexlendingbot-0.3/lendingbot.py", line 123, in <module>
    shutil.copy('default.cfg.example', 'default.cfg')
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'default.cfg.example'
```

when im in the bot directory everything works fine...

**Comment by Evanito** [comment]
The bot copies the configuration for you if you do not have one, but it
expects to be run in the context of its folder. Try doing `cd /your
folder/;python lendingbot.py`

**Comment by Evanito** [comment]
@judokan9 Should be fool-proof since last commit 🥇
