### ISSUE TITLE
PoloniexApiError: Internal error. Please try again. Requesting returnAvailableAccountBalances

### ISSUE THREAD

**Issue by sanitariu** [Mikadily/poloniexlendingbot#175]
PoloniexApiError: Internal error. Please try again. Requesting returnBalances
```
Unhandled error, please open a Github issue so we can fix it!
2017-01-07 03:34:06 Error: Internal error. Please try again. Requesting returnAvailableAccountBalances
Lended: [0.0689 BTC @ 0.0243%] Traceback (most recent call last):
  File "./lendingbot.py", line 64, in <module>
    Lending.cancel_all()
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Lending.py", line 99, in cancel_all
    available_balances = api.return_available_account_balances('lending')
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Poloniex.py", line 111, in return_available_account_balances
    balances = self.api_query('returnAvailableAccountBalances', {"account": account})
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Internal error. Please try again. Requesting returnAvailableAccountBalances

Unhandled error, please open a Github issue so we can fix it!
2017-01-07 05:15:20 Error: __init__() takes exactly 6 arguments (2 given)
Lended: [0.0689 BTC @ 0.0243%] Traceback (most recent call last):
  File "./lendingbot.py", line 64, in <module>
    Lending.cancel_all()
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Lending.py", line 99, in cancel_all
    available_balances = api.return_available_account_balances('lending')
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Poloniex.py", line 111, in return_available_account_balances
    balances = self.api_query('returnAvailableAccountBalances', {"account": account})
  File "/home/dri/miner/lending/poloniexlendingbot/modules/Poloniex.py", line 86, in api_query
    raise type(ex), type(ex)(ex.message + ' Requesting %s' % command), sys.exc_info()[2]
TypeError: __init__() takes exactly 6 arguments (2 given)

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by Evanito** [comment]
Thank you for creating an issue!
The first error seems like some Poloniex-side issue that we should suppress and silently retry, but the second one is possibly a bug. I will look into it.

**Comment by utdrmac** [comment]
Got similar to the above:

```
2017-01-12 07:13:33 Error: Internal error. Please try again. Requesting returnOpenLoanOffers
Traceback (most recent call last):
  File "lendingbot.py", line 68, in <module>
    Lending.cancel_all()
  File "/usr/src/poloniexlendingbot/modules/Lending.py", line 100, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "/usr/src/poloniexlendingbot/modules/Poloniex.py", line 129, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "/usr/src/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/usr/src/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Internal error. Please try again. Requesting returnOpenLoanOffers
```

**Comment by laxdog** [comment]
Can you close this @Evanito or @rnevet , the first is a polo error and the second is not handling it's error correctly which was fixed in https://github.com/Mikadily/poloniexlendingbot/pull/233
