### ISSUE TITLE
Poloniex DOGE minimum amount

### ISSUE THREAD

**Issue by dshopov** [Mikadily/poloniexlendingbot#182]
Hello,

Poloniex recently (yesterday) did a silent update and changed minimum loan size of coins.
They have changed it globally from 0.001 to 0.01 which can be changed easily via config (minloansize).

However for DOGE they require that lending amount is minimum 5 DOGE which is where the problem comes.

For now I have patched my Lending.py with the following code on line 184:

```python
if active_cur == "DOGE" and float(active_bal) < 5:
        log.log("DOGE amount under 5! Not lending!")
        return 0
````

It will be nice if we have minloansize in coinconfig and something default for such cases.

Regards,
Dimitar

**Comment by laxdog** [comment]
Similar problem with CLAM I think:

```
Welcome to Poloniex Lending Bot
Start of loop
update_conversion_rates
Started WebServer, lendingbot status available at http://localhost:33221/lendingbot.html
transfer_balances
cancel_all
lend_all
(u'CLAM', '0.31479349', '2', 0, 0.00039014999999999997)
2017-01-12 12:12:46 Error: Amount must be at least 1. Requesting createLoanOffer
Traceback (most recent call last):
  File "/home/dog/poloniexlendingbot/lendingbot.py", line 74, in <module>
    Lending.lend_all()
  File "/home/dog/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/dog/poloniexlendingbot/modules/Lending.py", line 218, in lend_cur
    create_lend_offer(active_cur, Decimal(active_bal) - lent, offer['rate'])
  File "/home/dog/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/dog/poloniexlendingbot/modules/Poloniex.py", line 175, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/dog/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/dog/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 1. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by rnevet** [comment]
This issue is already reported here:
https://github.com/Mikadily/poloniexlendingbot/issues/180

**Comment by laxdog** [comment]
Missed that, ta.
