### ISSUE TITLE
PoloniexApiError: Amount must be at least 0.01

### ISSUE THREAD

**Issue by ChrisG2711** [Mikadily/poloniexlendingbot#185]
Hello,

just doing first steps with my Raspberry Pi and Poloniexlendingbot (thanks for that great program!)
After starting I get this error message:

017-01-13 21:53:12 Error: Amount must be at least 0.01. Requesting createLoanOffer
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/pi/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/pi/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/pi/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!

Thanks in advance for checking!

Regards
Chris

**Comment by ChrisG2711** [comment]
I´ve just seen that this issue has already been raised.

**Comment by Evanito** [comment]
Hey! Welcome to the bot, I also run on a raspberry pi.
If you have the repo running from a clone, then all you have to do to get on the fixed branch is:
```
git checkout lending-rewrite
git pull
python lendingbot.py
```
and it should work just fine.

**Comment by ChrisG2711** [comment]
Hey,
thanks for that much easier way, as I´m totally new to Raspberry world I used the much more complicated way to copy the fixed code into new files. Much too learn here and great to see so much friendly support.
Have a great weekend!
