### ISSUE TITLE
autorenew takes too long when exiting

### ISSUE THREAD

**Issue by songproducer** [Mikadily/poloniexlendingbot#20]
Could be due to the huge number of tiny loans that need to renew, but it takes too long so I ctrl-c.

2016-02-19 16:05:39 AutoRenew loans... (Please Wait)
Lended: [xx.xxx BTC] 

^CTraceback (most recent call last):
  File "lendingbot.py", line 248, in <module>
    i = setAutoRenew(1);
  File "lendingbot.py", line 214, in setAutoRenew
    bot.toggleAutoRenew(int(item["id"]))
  File "/Users/leotreasure/poloniex/poloniexlendingbot/poloniex.py", line 160, in toggleAutoRenew
    return self.api_query('toggleAutoRenew',{"orderNumber":orderNumber})
  File "/Users/leotreasure/poloniex/poloniexlendingbot/poloniex.py", line 53, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt

**Comment by Mikadily** [comment]
Yes. It takes long. Minutes. It's experimental feature, and should be used with care. I should put a warning note about it.

**Comment by rnevet** [comment]
Sadly I couldn't find a better way to do it except looping over the loans and toggling them one by one.
Maybe I should remove the automatic feature and just make it a separate script - in case someone needs to switch all of his loans?

**Comment by songproducer** [comment]
This feature is a godsend as I've wrestled with the Poloniex interface manually before, cancelling one by one and it kept jumping around!

It would be nice to have as a separate script so if you just want to auto renew or cancel you don't necessarily need to start the loan script.

**Comment by Mikadily** [comment]
@rnevet I think showing progress would help a lot. e.g. (In progress.. 22 of 2054 loans completed)

**Comment by rnevet** [comment]
Added progress indication #22 - so we can close this ticket.

**Comment by songproducer** [comment]
Thanks this is very useful!
