### ISSUE TITLE
Lending amount below 0.01 not allowed and crashes.

### ISSUE THREAD

**Issue by eldok2** [Mikadily/poloniexlendingbot#201]
I know this is wrong, and that maybe it shouldn't be a bug, but ... I think that it should not crash and that is should be able to recover itself. Even if it keeps creating loans below minimum amount. 
```
2017-01-26 23:50:35 Error: Amount must be at least 0.01. Requesting createLoanOffer
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/opt/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/opt/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/opt/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/opt/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/opt/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/opt/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
2017-01-26 23:51:49 Error: Amount must be at least 0.01. Requesting createLoanOffer
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/opt/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/opt/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/opt/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/opt/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/opt/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/opt/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by Evanito** [comment]
Are you on the most recent version of master?
Updated in the last 24 hrs.

**Comment by eldok2** [comment]
It's a pretty new install. 
git branch -v
* master 40b8682 [behind 1] Only change working dir if needed (#177)

**Comment by rnevet** [comment]
Please update to the latest, issue is resolved there (was reported already multiple times).

**Comment by eldok2** [comment]
Done. I can see that the minloansize now is set up to be 0.01 or else it won't work. 
BTW, In the past this allowed me to place loans below that limit, maybe it shouldn't be able to do it, but it did.

**Comment by rnevet** [comment]
In the past minimum loan side was lower on Poloniex side, Poloniex recently updated those values and you can't place loans lower than 0.01 for any currency.
