### ISSUE TITLE
Error. Amount must be at least 1. Requesting createLoanOffer

### ISSUE THREAD

**Issue by zusanli** [Mikadily/poloniexlendingbot#202]
Hello there.
Does anybody know what to do?

Best greetings,
Sebastian

2017-01-29 12:59:52 Error: Amount must be at least 1. Requesting createLoanOffer
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/abuna/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/abuna/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/home/abuna/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/abuna/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/abuna/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/abuna/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 1. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
2017-01-29 13:01:02 Error: Amount must be at least 1. Requesting createLoanOffer
Traceback (most recent call last):
  File "lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/abuna/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/abuna/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/home/abuna/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/abuna/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/abuna/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/abuna/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 1. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!

**Comment by rnevet** [comment]
Update to latest version.

**Comment by zusanli** [comment]
Thank's a lot! It works again :)

**Comment by rnevet** [comment]
Your Welcome!
I recommend next time to search the closed issues as you might have found the answer there faster. :)
