### ISSUE TITLE
BadStatusLine:  Requesting returnLoanOrders

### ISSUE THREAD

**Issue by laxdog** [Mikadily/poloniexlendingbot#205]
Could just have been a time out, I'm not sure. I've not used used the market analysis stuff much. Thought I'd raise it anyway, maybe others are seeing it.

Running from lending-rewrite @ a2f14e451866ea7b70f1cfa46fbc0201b87ecf12

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dog/poloniexlendingbot/modules/MarketAnalysis.py", line 57, in update_market_loop
    update_markets()
  File "/home/dog/poloniexlendingbot/modules/MarketAnalysis.py", line 66, in update_markets
    raw_data = api.return_loan_orders(cur, 5)['offers'][0]
  File "/home/dog/poloniexlendingbot/modules/Poloniex.py", line 226, in return_loan_orders
    return self.api_query('returnLoanOrders', {"currency": currency, "limit": limit})
  File "/home/dog/poloniexlendingbot/modules/Poloniex.py", line 91, in api_query
    ret = urllib2.urlopen(urllib2.Request(req_url))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1217, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
BadStatusLine:  Requesting returnLoanOrders
```

**Comment by rnevet** [comment]
exception httplib.BadStatusLine
A subclass of HTTPException. Raised if a server responds with a HTTP status code that we don’t understand.

No idea.

(btw, please update lending-rewrite has been merged.) ;)
