### ISSUE TITLE
error said to open an issue

### ISSUE THREAD

**Issue by pumaro1208** [Mikadily/poloniexlendingbot#213]
```
Welcome to Poloniex Lending Bot
2017-02-04 18:00:51 Error: Amount must be at least 0.01. Requesting createLoanOffer
Traceback (most recent call last):
  File "/home/pumaro/poloniexlendingbot/lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/pumaro/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/pumaro/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/home/pumaro/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/pumaro/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/pumaro/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/pumaro/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by rnevet** [comment]
Please update to recent version, issue is resolved there.

**Comment by pumaro1208** [comment]
ok I updated to the latest version but had same error, so I added some more btc and now it seems to work.
How do I find the ip of the pythonanywhere?

Unhandled error, please open a Github issue so we can fix it!
2017-02-04 21:45:14 Error: Amount must be at least 0.01. Requesting createLoanOffer
Traceback (most recent call last):
  File "/home/pumaro/poloniexlendingbot/lendingbot.py", line 69, in <module>
    Lending.lend_all()
  File "/home/pumaro/poloniexlendingbot/modules/Lending.py", line 141, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/pumaro/poloniexlendingbot/modules/Lending.py", line 214, in lend_cur
    create_lend_offer(active_cur, sum_diff, offer['rate'])
  File "/home/pumaro/poloniexlendingbot/modules/Lending.py", line 95, in create_lend_offer
    msg = api.create_loan_offer(currency, amt, days, 0, rate)
  File "/home/pumaro/poloniexlendingbot/modules/Poloniex.py", line 174, in create_loan_offer
    "lendingRate": lending_rate, })
  File "/home/pumaro/poloniexlendingbot/modules/Poloniex.py", line 80, in api_query
    json_ret = _read_response(ret)
  File "/home/pumaro/poloniexlendingbot/modules/Poloniex.py", line 46, in _read_response
    raise PoloniexApiError(data['error'])
PoloniexApiError: Amount must be at least 0.01. Requesting createLoanOffer

Unhandled error, please open a Github issue so we can fix it!
2017-02-04 21:46:16 Placing 0.04168653 BTC at 0.0248% for 2 days... Loan order placed.
Lended: [29.9996 BTC @ 0.0246%]

**Comment by Evanito** [comment]
You should not get that error on the latest `master` at all. Please double check that you are up to date.
Pythonanywhere's ip address is linked to your account, as you can see here: https://poloniexlendingbot.readthedocs.io/en/latest/installation.html#creating-the-web-app-optional

**Comment by pumaro1208** [comment]
Can you post a link to the correct version. I am also getting an error on the Web page.
Poloniex Lending Bot

Not updated
Status	getJSON failed, status: error, error: Not Found
Log (Reversed ordered):

**Comment by rnevet** [comment]
If your are using git, make sure you are on master and pull latest - that's the correct version.

If you are using a zipped version, we don't have an updated release, so you should download the zip this way:
![image](https://cloud.githubusercontent.com/assets/1645822/22628262/40c800d8-ebd1-11e6-9c98-10c4c16e3bef.png)

**Comment by pumaro1208** [comment]
downloaded the latest file and it works now! thanks
