### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by geostoned** [Mikadily/poloniexlendingbot#214]
```
Welcome to Poloniex Lending Bot
Started WebServer, lendingbot status available at http://localhost:8000/lendingbot.html
2017-02-04 16:08:41 Error: __init__() takes exactly 6 arguments (2 given)
Traceback (most recent call last):
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\lendingbot.py", line 68, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Data.py", line 82, in update_conversion_rates
    total_lended = get_total_lended()[0]
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Data.py", line 44, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Poloniex.py", line 160, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "C:\Users\Geo\Desktop\poloniexlendingbot-master\modules\Poloniex.py", line 111, in api_query
    raise type(ex), type(ex)(ex.message + ' Requesting %s' % command), sys.exc_info()[2]
TypeError: __init__() takes exactly 6 arguments (2 given)

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by rnevet** [comment]
Was it working before or is this a new setup?

**Comment by geostoned** [comment]
It's new, I think. This is my first report so I honestly didn't pay
attention before I would just restart it when I had issues. I'll try to
start paying more attention.

**Comment by rnevet** [comment]
Is the bot working otherwise?

**Comment by rnevet** [comment]
Ok, it is already reported, https://github.com/Mikadily/poloniexlendingbot/issues/181

Not that I have a solution yet.

**Comment by geostoned** [comment]
As far as I can tell it is working fine. I appreciate your quick responses
and apologize for reporting the same issue.

**Comment by rnevet** [comment]
Not a problem.
