### ISSUE TITLE
Error: <urlopen error [Errno 11001] getaddrinfo failed>

### ISSUE THREAD

**Issue by ammbyrne** [Mikadily/poloniexlendingbot#234]
Upon Launching.

Welcome to Poloniex Lending Bot
2017-02-16 17:53:27 Error: <urlopen error [Errno 11001] getaddrinfo failed> Requesting returnOpenLoanOffers
Traceback (most recent call last):
  File "C:\Python27\Poloniex\poloniexlendingbot-master\lendingbot.py", line 70, in <module>
    Lending.cancel_all()
  File "C:\Python27\Poloniex\poloniexlendingbot-master\modules\Lending.py", line 118, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "C:\Python27\Poloniex\poloniexlendingbot-master\modules\Poloniex.py", line 153, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "C:\Python27\Poloniex\poloniexlendingbot-master\modules\Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Unhandled error, please open a Github issue so we can fix it!

**Comment by rnevet** [comment]
Does this persist? 

Your bot doesn't manage to resolve the poloniex address, could be a DNS issue.
try pinging poloniex.com

**Comment by Magicxiangye** [comment]
same bug in URLerror didn't know how to deal

**Comment by Evanito** [comment]
> same bug in URLerror didn't know how to deal

This bug is likely due to temporary internet issues between you and the exchange. You can expect it to resolve itself in most situations.
