### ISSUE TITLE
Error: __init__() takes exactly 6 arguments (2 given)

### ISSUE THREAD

**Issue by Bonez0r** [Mikadily/poloniexlendingbot#235]
The master version i use is from 1 Feb, so it may have been fixed in the meantime. It may also be that i made a mistake in the config (i hope not), in which case i'm wasting your time. :(

Here's the error in the output window:

```
2017-02-17 01:10:16 Error: __init__() takes exactly 6 arguments (2 given)
Lended: [28.0422 BTC @ 0.0191%] [1668.1705 MAID @ 0.1014%] [26.7504 XMR @ 0.0173%] Traceback (most recent call last):
  File "L:\temp\bitcoin\poloniexlendingbot-master_new\lendingbot.py", line 70, in <module>
    Lending.cancel_all()
  File "L:\temp\bitcoin\poloniexlendingbot-master_new\modules\Lending.py", line 118, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "L:\temp\bitcoin\poloniexlendingbot-master_new\modules\Poloniex.py", line 154, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "L:\temp\bitcoin\poloniexlendingbot-master_new\modules\Poloniex.py", line 111, in api_query
    raise type(ex), type(ex)(ex.message + ' Requesting %s' % command), sys.exc_info()[2]
TypeError: __init__() takes exactly 6 arguments (2 given)

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by laxdog** [comment]
This should have been fixed in https://github.com/Mikadily/poloniexlendingbot/pull/233

Try doing a pull and running from head.

**Comment by rnevet** [comment]
Please reopen if appears after updating.
