### ISSUE TITLE
autorenew crashes

### ISSUE THREAD

**Issue by songproducer** [Mikadily/poloniexlendingbot#24]
2016-03-04 18:39:36 Clearing AutoRenew...(Please Wait)
Processing AutoRenew - 223 of 1815 loansTraceback (most recent call last):
  File "lendingbot.py", line 237, in <module>
    setAutoRenew(0);
  File "lendingbot.py", line 227, in setAutoRenew
    bot.toggleAutoRenew(int(item["id"]))
  File "/Users/leotreasure/poloniex/poloniexlendingbot/poloniex.py", line 160, in toggleAutoRenew
    return self.api_query('toggleAutoRenew',{"orderNumber":orderNumber})
  File "/Users/leotreasure/poloniex/poloniexlendingbot/poloniex.py", line 53, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

**Comment by rnevet** [comment]
1. Was this the end of the error log? can you provide the rest?
2. Does it always happen?

**Comment by songproducer** [comment]
1. This was all the result from Terminal. Not sure where any log file is.
2. Yes

**Comment by songproducer** [comment]
Actually, regarding point 2, it worked this time.

**Comment by songproducer** [comment]
Haven't encountered the crashing error for some time now - closing :)
