### ISSUE TITLE
Error: HTTP Error 403: Forbidden Requesting returnOpenLoanOffers

### ISSUE THREAD

**Issue by KDragonM** [Mikadily/poloniexlendingbot#242]
After changing notify_summary_minutes to a number to fix #241, I ran into this error message

```
pi@raspberrypi:~/Programs/poloniexlendingbot $ python lendingbot.py
Welcome to Poloniex Lending Bot
2017-02-25 07:53:11 Error: HTTP Error 403: Forbidden Requesting returnOpenLoanOffers
Traceback (most recent call last):
  File "lendingbot.py", line 71, in <module>
    Lending.cancel_all()
  File "/home/pi/Programs/poloniexlendingbot/modules/Lending.py", line 137, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "/home/pi/Programs/poloniexlendingbot/modules/Poloniex.py", line 153, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "/home/pi/Programs/poloniexlendingbot/modules/Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by rnevet** [comment]
Did it work before? 403 forbidden means that poloniex is rejecting your access.

There was another issue opened on this:
https://github.com/Mikadily/poloniexlendingbot/issues/121

**Comment by laxdog** [comment]
This is unrelated to the other issue you had. 

Have you used this API key with the bot before? 
Can you access poloniex.com through a browser on your pi? 

I don't think this is a problem with the bot code, I'm guessing key or firewall. Which is why I asked those questions. 

Cancel_all is one of the first calls we make, and that's where is bombing out.

**Comment by KDragonM** [comment]
Whoops, I had changed some settings on Poloniex so it wasn't working. Thanks for the quick response!

**Comment by KaufNation** [comment]
How did you fix this..? Having the same issue

Thanks

**Comment by KDragonM** [comment]
I think the problem was that the API keys had been revoked after activating 2FA or something like that. I remember it was some problem with the API settings/keys on poloniex.

**Comment by KaufNation** [comment]
Do you remember how you fixed it? I double checked that I have the right secret and key. But it is still throwing an error. Should I create a new key and delete the old set?

**Comment by manzabi** [comment]
I believe you have to enable 2FA first, then request api key. 
I had the same problem, solved disabling 2FA and re-enabling it
