### ISSUE TITLE
Errors when running the latest release

### ISSUE THREAD

**Issue by Kevmate** [Mikadily/poloniexlendingbot#258]
I am getting errors during the run, which it says I should report here. It looks like there are two different errors. Here is the full output log (with some of the boring bits removed)...

WARN: Module Numpy not found, using manual percentile method instead. It is recommended to install Numpy. Error: No module named numpy
Welcome to Poloniex Lending Bot
2017-03-11 16:09:14 Canceling all DASH orders... Loan offer canceled.
...etc...
2017-03-11 17:18:56 Canceling all DASH orders... Loan offer canceled.
2017-03-11 17:18:57 Not lending DASH due to rate below 0.2495%
2017-03-11 17:18:59 Not lending FCT due to rate below 0.0200%
2017-03-11 17:30:01 Error: The read operation timed out Requesting returnAvailableAccountBalances
Lended: [4198.6713 DASH @ 0.1853%] [203.8966 ETH @ 0.0069%] Timed out, will retry in 600.0sec
2017-03-11 17:40:39 Not lending DASH due to rate below 0.2477%
2017-03-11 17:40:40 Not lending FCT due to rate below 0.0200%
2017-03-11 17:40:40 Error: HTTP Error 502: Bad Gateway Requesting returnActiveLoans
Lended: [4198.6713 DASH @ 0.1853%] [203.8966 ETH @ 0.0069%] Traceback (most recent call last):
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\lendingbot.py", line 73, in <module>
    log.refreshStatus(Data.stringify_total_lended(*Data.get_total_lended()), Data.get_max_duration(
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Data.py", line 45, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 159, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 502: Bad Gateway

Unhandled error, please open a Github issue so we can fix it!
2017-03-11 17:51:35 Placing 15.62615210 DASH at 0.2487% for 28 days... Loan order placed.
...etc...
2017-03-11 18:49:36 Not lending FCT due to rate below 0.0200%
2017-03-11 19:00:19 Error: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> Requesting returnActiveLoans
Lended: [4180.5354 DASH @ 0.1762%] [203.8966 ETH @ 0.0069%] Traceback (most recent call last):
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\lendingbot.py", line 72, in <module>
    Lending.lend_all()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 168, in lend_all
    total_lended = Data.get_total_lended()[0]
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Data.py", line 45, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 159, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Unhandled error, please open a Github issue so we can fix it!
2017-03-11 19:10:22 Not lending DASH due to rate below 0.2477%
2017-03-11 19:10:23 Not lending FCT due to rate below 0.0200%
...etc...
2017-03-11 22:11:27 Placing 65.85774675 DASH at 0.465162857143% for 28 days... Loan order placed.
2017-03-11 22:12:09 Error: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> Requesting createLoanOffer
Lended: [3797.8005 DASH @ 0.2159%] [34.8966 ETH @ 0.0139%] Traceback (most recent call last):
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\lendingbot.py", line 72, in <module>
    Lending.lend_all()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 181, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 330, in lend_cur
    raise msg
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Unhandled error, please open a Github issue so we can fix it!
2017-03-11 22:14:13 Placing 49.74254305 DASH at 0.4919% for 28 days... Loan order placed.
...etc...
2017-03-12 00:03:24 Not lending ETH due to rate below 0.0200%
2017-03-12 00:04:06 Error: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> Requesting returnLoanOrders
Lended: [4190.8061 DASH @ 0.2328%] [34.8966 ETH @ 0.0139%] Traceback (most recent call last):
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\lendingbot.py", line 72, in <module>
    Lending.lend_all()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 181, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 293, in lend_cur
    order_book = construct_order_book(active_cur)
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 211, in construct_order_book
    loans = api.return_loan_orders(active_cur, loanOrdersRequestLimit[active_cur])
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 225, in return_loan_orders
    return self.api_query('returnLoanOrders', {"currency": currency, "limit": limit})
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 91, in api_query
    ret = urllib2.urlopen(urllib2.Request(req_url))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Unhandled error, please open a Github issue so we can fix it!
2017-03-12 00:14:30 Placing 45.20157124 DASH at 0.4499% for 28 days... Loan order placed.
...etc...
2017-03-12 01:01:55 Placing 14.86409459 DASH at 0.4205% for 28 days... Loan order placed.
2017-03-12 01:02:37 Error: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> Requesting createLoanOffer
Lended: [4125.3484 DASH @ 0.2330%] [34.8966 ETH @ 0.0139%] Traceback (most recent call last):
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\lendingbot.py", line 72, in <module>
    Lending.lend_all()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 181, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 330, in lend_cur
    raise msg
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Unhandled error, please open a Github issue so we can fix it!
2017-03-12 01:04:40 Placing 26.20159979 DASH at 0.3694% for 28 days... Loan order placed.
...etc...
2017-03-12 02:15:50 Not lending FCT due to rate below 0.0200%
2017-03-12 02:26:54 Error: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> Requesting returnActiveLoans
Lended: [3832.1941 DASH @ 0.2228%] [34.8966 ETH @ 0.0139%] Traceback (most recent call last):
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\lendingbot.py", line 72, in <module>
    Lending.lend_all()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 168, in lend_all
    total_lended = Data.get_total_lended()[0]
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Data.py", line 45, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 159, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Unhandled error, please open a Github issue so we can fix it!
2017-03-12 02:36:55 Canceling all DASH orders... Loan offer canceled.
2017-03-12 02:36:57 Not lending DASH due to rate below 0.3024%
...etc...
2017-03-12 16:52:33 Not lending FCT due to rate below 0.0200%
2017-03-12 17:02:37 Error: list indices must be integers, not Decimal
Lended: [3639.7303 DASH @ 0.3032%] [34.8966 ETH @ 0.0139%] Traceback (most recent call last):
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\lendingbot.py", line 72, in <module>
    Lending.lend_all()
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 181, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 305, in lend_cur
    orders = construct_orders(active_cur, active_bal)  # Construct all the potential orders
  File "C:\Users\kev\Bitcoins\poloniexlendingbot-master\modules\Lending.py", line 269, in construct_orders
    order_rates[rate] = max_daily_rate
TypeError: list indices must be integers, not Decimal

Unhandled error, please open a Github issue so we can fix it!

**Comment by laxdog** [comment]
Hey @Kevmate , the HTTP Error 502 should be handled properly in the very latest code, that was only merged last night, so you might need to do a pull. 

The Errno 10060 looks to be a problem on the Poloniex side, there's not much we can do about it aside from handle the error a bit more gracefully, I haven't actually seen that error in a while, but it should be possible to put a patch in to handle.

The last one I *think* is just a symptom of the previous error. Though I'm not quite sure. 

Is the bot still running?

**Comment by Kevmate** [comment]
Yes - well - i restarted it. I think it stopped after the last error. I'm
confused about the numpy error at the start. I tried installing numpy but
got confused. I think I need a different python install but struggling atm.
Thanks for your help :)

**Comment by Kevmate** [comment]
oh - while you are on - there is no such word as "lended". Its "loaned" -
or you could use "Loan completed"

**Comment by laxdog** [comment]
The easiest way to install numpy is with pip.

Just google installing pip for python on windows. 

Then you can do 

`pip install numpy`

Noted on the lended point too.

**Comment by Kevmate** [comment]
sorry to keep emailing you, but I got a line saying:
2017-03-12 19:30:01 Not lending DASH due to rate below 0.2896%

But my minimum load rate for Dash is set at .09

I am watching it and indeed is seems to be leaving dash unloaned

Thanks

k

**Comment by rnevet** [comment]
We know that "lended" is a mistake, just didn't get to renaming it to "lent" ;)

**Comment by rnevet** [comment]
@Kevmate have you updated the bot to the latest version?
There were issues with Market Analysis which I assume from the log that you have enabled where the bot would stop collecting data. Otherwise review your Market Analysis settings and data files... might be that DASH rates were very high recently.

**Comment by Kevmate** [comment]
I have installed the latest version, although its hard to see the version
number in the installed software to be completely sure. Maybe you should
put it in the output log, and perhaps also in the readme.

Yes, I have switched on market analysis, although I haven't looked at the
data yet. However, you are right, DASH rates were very high today, maybe
thats all it is.

Will watch

Many thanks

K

**Comment by rnevet** [comment]
@Kevmate after the last commit (now) URLError, HttpError and PoloniexApiError will only be logged without exception trace. (bot will continue)

**Comment by Kevmate** [comment]
Thanks for that. Still testing.

A couple of things:

1. Actually, I am a Dash man, not bitcoin. If you create a Dash wallet and
put it in your link I will send you 1 dash. This works for me because its a
little advert for dash - which I like the idea of. I'm hoping you keep the
wallet open for future people like me. Dash is $100 atm so its worth having.

2. I am still confused about this "Not lending DASH due to rate below
0.2973% message. I put same dash up for lending and .273 and started the
bot, and it cancelled my load offer. Why cancel a load offer at that high
rate? My min load percentage is low. My dash went back into my lending
wallet and stayed there.

Many thanks

Kevin

**Comment by rnevet** [comment]
Hi Kevin,
1. Is there a Dash multisig wallet like copay?
2. The bot isn't built to allow you to manually loan the coin it manages, it cancels all offers every cycle and places new offers. You might consider disabling market analysis or reducing the timespan to make it more dynamic.

**Comment by laxdog** [comment]
Hey @Kevmate 

The log statement "Not lending DASH due to rate below 0.2973% message" is shown when two things are True. 
1) The hideCoins config is set to True. 
2) The best loan rate in the market is below the current min daily rate. i.e. the loan the bot would make, would be the same as the min daily rate.

This means if the loan the bot wanted to make at say 0.2 and the mindaily rate 0.25, instead of making a loan at 0.25, it will not make any loan at all. 
In your case the min daily rate has been set by the MarketAnalysis module. It has looked at the rates for the times you have configured and suggested what the min daily rate should be. 
This is done to not give information away to the market. If hideCoins was False, it would have made a loan at 0.2973, though this likely would not have been accepted straight away as the market rates were below this. Thus your loan was 'hidden'

The first thing the bot does when it starts is cancel all open loans that you have, this is so it has full control over the balances. So if there was a loan already in your account for 0.273 the bot would have canceled this. 

If you are unsure about the MarketAnalysis you can turn it off. It will always change the min daily rate for each coin as it analyses its data otherwise.

You could also turn off hideCoins, so you will always have loans in the book if you have coins to do so.

You can also reduce how aggressive the lending style is. The number for the lending style is a percentage, where it will work out what lending rate is required for x% of the results to be below the value you have specified in the data it has collected. 

We are currently working on a new market analysis strategy using MACD (Moving averages) that is a bit more reactive and could help, if you still wish to use market analysis to get better rates.

**Comment by Kevmate** [comment]
Hi Michael,

This is very confusing.

However, I am gradually catching on. hideCoins was True, and
analysisCurrencies was DASH, and lendingStyle was 75. I didn't understand
what was meant by Conservative and Aggressive. I think I am getting it now.
Agressive means set a high rate even if that means coins don't get loaned.

I will play with the numbers in the light of this, and download a new
version.

Any plans to accept Dash contributions to the cause?

Kevin

**Comment by laxdog** [comment]
Agreed, it is quite confusing. I had to re-read the source to be sure myself. 

If you set it to 75, that means it takes the 75th percentile of the values it has recorded. So, whatever value is found to have 75% of the other values recorded below it. 

Aggressive means exactly that. If you were to put it at 100% for example, it would never make a loan unless it was exactly the same as the highest loan recorded.

If you still want to use it, I'd recommend dropping the style to 50% and keeping an eye out for those log messages now you know what is causing them. It' recommended to use numpy for this.

I think once someone works out how to create a multi signature wallet, Dash contributions will most certainly be accepted :)

**Comment by laxdog** [comment]
I'd take that advice then instead, I've not used it as much.

**Comment by Kevmate** [comment]
In fact thats more or less where I have the numbers. I was using 30%, then
raised it to 40% and am keeping it there, and I chose 3 days. This is quite
far from the defaults. I agree that the market changes so quickly that you
have to go with the moment really. Does this number accept decimals?

I will make a suggestion to the dash developers for multi-sig wallets. They
are always looking for new ideas.

Best regards

K

**Comment by Kevmate** [comment]
I had a little search in the dash forum for progress on multisig wallets
and found that there is an old way of doing it, which looks rather
technical, and a new way, which will be great when it arrives, but is still
only beta.

You might think its not worth the trouble, unless you are interested in
dash. I think dash is brill.

Here is the text...

*New*You can see more details here:
https://dashpay.atlassian.net/wiki/display/DOC/Complex+Multisignature+Example

It is a bit old and you should substitute Darkcoin for Dash where
appropriate, but it works exactly like that and I've made many transactions
like that (someday I will update that page!).

Recently the Evolution development team ported to Dash Bitpay's Copay
wallet. It is still very beta, but you can give it a go if you feel like it:
https://www.dash.org/forum/threads/copay-dash-wallet-testnet-only-rc-0-1.12930/

Dash Electrum also has multisig, but I have not used it.

K

**Comment by laxdog** [comment]
You can only use integers in the lending style config. 

I'll have a read at those.
