### ISSUE TITLE
Noob error most likely

### ISSUE THREAD

**Issue by shimoda** [Mikadily/poloniexlendingbot#288]
I am trying to run the bot on pythonanywhere. Have installed and configured (mostly default settings)
On start I get following trace:
Traceback (most recent call last):
  File "/home/shimoda94/poloniexlendingbot/lendingbot.py", line 54, in <module>
    analysis = MarketAnalysis(Config, api)
  File "/home/shimoda94/poloniexlendingbot/modules/MarketAnalysis.py", line 24, in __init__
    self.currencies_to_analyse = config.get_currencies_list('analyseCurrencies')
  File "/home/shimoda94/poloniexlendingbot/modules/Configuration.py", line 121, in get_currencies_list
    cur_list += Data.get_lending_currencies()
  File "/home/shimoda94/poloniexlendingbot/modules/Data.py", line 126, in get_lending_currencies
    total_lended = get_total_lended()[0]
  File "/home/shimoda94/poloniexlendingbot/modules/Data.py", line 45, in get_total_lended
    crypto_lended = api.return_active_loans()
  File "/home/shimoda94/poloniexlendingbot/modules/Poloniex.py", line 159, in return_active_loans
    return self.api_query('returnActiveLoans')
  File "/home/shimoda94/poloniexlendingbot/modules/Poloniex.py", line 104, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422: 

Can not see any error in config file. Any help appreciated

**Comment by rnevet** [comment]
I'm guessing it's an issue with the Key/Secret but... can you try disabling MarketAnalysis in the config?

**Comment by shimoda** [comment]
Yes, I was reusing an other API key. Ok now. Thanks for fast reply
