### ISSUE TITLE
Unhandled error [Errno 10054]

### ISSUE THREAD

**Issue by qwertysc** [Mikadily/poloniexlendingbot#297]
[Errno 10054] 
-------
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\poloniexlendingbot\lendingbot.py", line 72, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "C:\Users\Administrator\Desktop\poloniexlendingbot\modules\Data.py", line 84, in update_conversion_rates
    ticker_response = api.return_ticker()
  File "C:\Users\Administrator\Desktop\poloniexlendingbot\modules\Poloniex.py", line 113, in return_ticker
    return self.api_query("returnTicker")
  File "C:\Users\Administrator\Desktop\poloniexlendingbot\modules\Poloniex.py", line 77, in api_query
    return _read_response(ret)
  File "C:\Users\Administrator\Desktop\poloniexlendingbot\modules\Poloniex.py", line 69, in _read_response
    data = json.loads(resp.read())
  File "C:\Python27\lib\socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "C:\Python27\lib\httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "C:\Python27\lib\httplib.py", line 642, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "C:\Python27\lib\httplib.py", line 688, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 766, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 653, in read
    v = self._sslobj.read(len)
error: [Errno 10054]

**Comment by rnevet** [comment]
Thanks for reporting, this is a communication error, the bot will recover.

We should adjust error handling for 'socket.error' types.

**Comment by laxdog** [comment]
Would be good to implement a retry as mentioned here:

https://stackoverflow.com/questions/18832643/how-to-catch-this-python-exception-error-errno-10054-an-existing-connection
