### ISSUE TITLE
Error in module cancelAndLoanAll

### ISSUE THREAD

**Issue by xR2** [Mikadily/poloniexlendingbot#83]
Actually I get the following errors:

```
Traceback (most recent call last): File "C:\poloniexlendingbot-master\lendingbot.py", line 459, in <module> cancelAndLoanAll() 
File "C:\poloniexlendingbot-master\lendingbot.py", line 319, in cancelAndLoanAll loans = bot.returnLoanOrders(activeCur, loanOrdersRequestLimit[activeCur] ) 
File "C:\poloniexlendingbot-master\poloniex.py", line 161, in returnLoanOrders return self.api_queryereturnLoanOrders'Xcurrency":currency,
File "C:\poloniexlendingbot-master\poloniex.py", line 45, in api_query ret = urllib2.urlopen(urllib2.Request(reqUr1)) 
File "C:\Python27\lib\urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) 
File "C:\Python27\lib\urllib2.py", line 437, in open response = meth(req, response) 
File "C:\Python27\lib\urllib2.py", line 550, in http_response 'http', request, response, code, msg, hdrs) 
File "C:\Python27\lib\urllib2.py", line 475, in error return self._call_chain(*args) 
File "C:\Python27\lib\urllib2.py", line 409, in _call_chain result = func(*args) 
File "C:\Python27\lib\urllib2.py", line 558, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) 
HTTPError: HTTP Error 521: Origin Down 
```
And i'm not sure if I should worry about or what have I config wrong.

**Comment by rnevet** [comment]
I've been looking into this issue, poloniex support suggested that it happens because of "http" instead of "https" calls.

I created a fix branch here:
https://github.com/Mikadily/poloniexlendingbot/tree/error521

Please give feedback if that fixes the issue for you.

**Comment by Evanito** [comment]
I have noticed recent crashes on my setup as well

**Comment by rnevet** [comment]
Pull request is here:
https://github.com/Mikadily/poloniexlendingbot/pull/84

**Comment by xR2** [comment]
@rnevet Many thanks! That seems to work like a charm for me, running your version since your reply and till now no error so far.

**Comment by xR2** [comment]
Sorry but it happening again with `cancelAndLoadAll`.

![task2](https://cloud.githubusercontent.com/assets/17341234/16624312/95079968-4377-11e6-8d1d-89249eb13ba7.png)

**Comment by rnevet** [comment]
That's not the same error, the one fixed is the Http error 521.
