### ISSUE TITLE
<module> refreshTotalLended() 

### ISSUE THREAD

**Issue by xR2** [Mikadily/poloniexlendingbot#87]
I'm not sure if this is related to the SSL Error in the last line but this is what I got:

```
Started WebServer, lendingbot status available at http://127.0.0.1:8000/lendingbot.html 
Traceback (most recent call last): 
File "C:\poloniexlendingbot-master\lendingbot.py", line 457, in <module> refreshTotalLended() 
File "C:\poloniexlendingbot-master\lendingbot.py", line 223, in refreshTotalLended cryptoLended = bot.returnActiveLoans() 
File "C:\poloniexlendingbot-master\poloniex.py", line 101, in returnActiveLoans return self.api_query('returnActiveLoans') 
File "C:\poloniexlendingbot-master\poloniex.py", line 58, in api_query ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers)) 
File "C:\Python27\lib\urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) 
File "C:\Python27\lib\urllib2.py", line 431, in open response = self._open(req, data) 
File "C:\Python27\lib\urllib2.py", line 449, in _open '_open', req) File "C:\Python27\lib\urllib2.py", line 409, in _call_chain result = func(*args) 
File "C:\Python27\lib\urllib2.py", line 1240, in https_open context.self._context) 
File "C:\Python27\lib\urllib2.py", line 1200, in do_open r = h.getresponse(buffering=True) 
File "C:\Python27\lib\httplib.py", line 1132, in getresponse response. begin() 
File "C:\Python27\lib\httplib.py", line 453, in begin version, status, reason = self._read_status() 
File "C:\Python27\lib\httplib.py", line 409, in _read_status line = self.fp.readline( MAXLINE + 1) 
File "C:\Python27\lib\socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) 
File "C:\Python27\lib\ssl.py", line 734, in recv return self.read(buflen) 
File "C:\Python27\lib\ssl.py", line 621, in read v = self._sslobj.read(len or 1024) 
SLError: ('The read operation timed out',) 

```

**Comment by rnevet** [comment]
As it says, 'The read operation timed out'.

**Comment by xR2** [comment]
So it's basically just my internet been slow. Fair, is there a way to increase the timeout ?
Or this doesn't stop the bot at all? I mean does not require-me to restart lendingbot.py?

**Comment by rnevet** [comment]
@xR2 Issue closed?

**Comment by xR2** [comment]
Oh, yes yes, closed.
