### ISSUE TITLE
KeyError: 'provided' in refreshTotalLended

### ISSUE THREAD

**Issue by xR2** [Mikadily/poloniexlendingbot#89]
Does this means my API has expired or that I've configured refresh (`sleeptimeactive`) too fast?

```
Traceback (most recent call last): 
File "C:\poloniexlendingbot-master\lendingbot.py", line 457, in <module> refreshTotalLended() 
File "C:\poloniexlendingbot-master\lendingbot.py", line 230, in refreshTotalLended for item in cryptoLended["provided"]: 
KeyError: 'provided'
```

This error keeps repeating, flooding the prompt window.

**Comment by xR2** [comment]
My ip has changed, so I had to edit the `API Trusted IP`.

**Comment by Evanito** [comment]
We need a troubleshooting section

**Comment by rnevet** [comment]
Like this one:
https://github.com/Mikadily/poloniexlendingbot/wiki/FAQ-(Trouble-shooting)
